### ISSUE TITLE
"Wrong type argument: sequencep, j"

### ISSUE THREAD

**Issue by zobi8225** [renard/o-blog#134]
Hi,
I am little bit noob on o-blog.
I don't understand the problem 
> .emacs.d/o-blog/lisp/o-blog-backend.el:Error: Wrong type argument: sequencep, j

I am on manual install (git) on (24.4.1)

**Comment by amsomniac** [comment]
I also have this problem. No idea what it is either.

**Comment by amsomniac** [comment]
Here's what it looks like with debug on:
Org-mode version 8.3 beta, Emacs 24.3.50.1

<code>
Debugger entered--Lisp error: (wrong-type-argument sequencep j)
  mapcar(byte-optimize-form j)
  byte-optimize-form-code-walker((i . j) nil)
  byte-optimize-form((i . j))
  mapcar(byte-optimize-form (for (i . j) on tags with k = 1 when (and j (string= ... ...)) do (incf k) else collect (progn (when ... ...) (when ... ...) (list k i)) and do (setf k 1)))
  byte-optimize-form-code-walker((loop for (i . j) on tags with k = 1 when (and j (string= ... ...)) do (incf k) else collect (progn (when ... ...) (when ... ...) (list k i)) and do (s$
  byte-optimize-form((loop for (i . j) on tags with k = 1 when (and j (string= ... ...)) do (incf k) else collect (progn (when ... ...) (when ... ...) (list k i)) and do (setf k 1)))
  mapcar(byte-optimize-form (for (count tag) in (loop for (i . j) on tags with k = 1 when (and j ...) do (incf k) else collect (progn ... ... ...) and do (setf k 1)) do (progn (set-slo$
  byte-optimize-form-code-walker((loop for (count tag) in (loop for (i . j) on tags with k = 1 when (and j ...) do (incf k) else collect (progn ... ... ...) and do (setf k 1)) do (prog$
  byte-optimize-form((loop for (count tag) in (loop for (i . j) on tags with k = 1 when (and j ...) do (incf k) else collect (progn ... ... ...) and do (setf k 1)) do (progn (set-slot-$
  mapcar(byte-optimize-form (self (quote tags) (loop for (count tag) in (loop for ... on tags with k = 1 when ... do ... else collect ... and do ...) do (progn ... ...) collect tag)))
  byte-optimize-form-code-walker((set-slot-value self (quote tags) (loop for (count tag) in (loop for ... on tags with k = 1 when ... do ... else collect ... and do ...) do (progn ... $
  byte-optimize-form((set-slot-value self (quote tags) (loop for (count tag) in (loop for ... on tags with k = 1 when ... do ... else collect ... and do ...) do (progn ... ...) collect$
  byte-optimize-body(((set-slot-value self (quote tags) (loop for ... in ... do ... collect tag))) nil)
  byte-optimize-form-code-walker((let* ((tags-art ...) (tags-page ...) (tags ...) (min_r ...) (max_r ...) (min_f ...) (max_f 0)) (set-slot-value self (quote tags) (loop for ... in ... $
  byte-optimize-form((let* ((tags-art ...) (tags-page ...) (tags ...) (min_r ...) (max_r ...) (min_f ...) (max_f 0)) (set-slot-value self (quote tags) (loop for ... in ... do ... colle$
  byte-optimize-form-code-walker((progn (let* (... ... ... ... ... ... ...) (set-slot-value self ... ...))) nil)
  byte-optimize-form((progn (let* (... ... ... ... ... ... ...) (set-slot-value self ... ...))) nil)
  byte-compile-top-level((progn (let* (... ... ... ... ... ... ...) (set-slot-value self ... ...))) nil lambda)
  byte-compile-lambda((lambda (self &optional min_r max_r) "Return a sorted list of all ob:tags by name.\n\nCompute tag occurrence and their HTML percentage value.\n\nMIN_R and MAX_R a$
  byte-compile-function-form((function (lambda (self &optional min_r max_r) "Return a sorted list of all ob:tags by name.\n\nCompute tag occurrence and their HTML percentage value.\n\n$
  byte-compile-form((function (lambda (self &optional min_r max_r) "Return a sorted list of all ob:tags by name.\n\nCompute tag occurrence and their HTML percentage value.\n\nMIN_R and$
  mapc(byte-compile-form ((function (lambda ... "Return a sorted list of all ob:tags by name.\n\nCompute tag occurrence and their HTML percentage value.\n\nMIN_R and MAX_R are the mini$
  byte-compile-normal-call((apply (function (lambda ... "Return a sorted list of all ob:tags by name.\n\nCompute tag occurrence and their HTML percentage value.\n\nMIN_R and MAX_R are $
  byte-compile-funarg((apply (quote (lambda ... "Return a sorted list of all ob:tags by name.\n\nCompute tag occurrence and their HTML percentage value.\n\nMIN_R and MAX_R are the mini$
  byte-compile-form((apply (quote (lambda ... "Return a sorted list of all ob:tags by name.\n\nCompute tag occurrence and their HTML percentage value.\n\nMIN_R and MAX_R are the minimu$
  byte-compile-body(((apply (quote ...) local-args)) nil)
  byte-compile-let((let ((scoped-class ...) (eieio-generic-call-next-method-list nil) (eieio-generic-call-key method-primary) (eieio-generic-call-methodname ...) (eieio-generic-call-ar$
  byte-compile-form((let ((scoped-class ...) (eieio-generic-call-next-method-list nil) (eieio-generic-call-key method-primary) (eieio-generic-call-methodname ...) (eieio-generic-call-a$
  byte-compile-body(((let (... ... ... ... ...) (apply ... local-args))) nil)
  byte-compile-if((if (not (child-of-class-p ... ...)) (apply (quote no-applicable-method) (car local-args) (quote ob:compute-tags) local-args) (let (... ... ... ... ...) (apply ... lo$
  byte-compile-form((if (not (child-of-class-p ... ...)) (apply (quote no-applicable-method) (car local-args) (quote ob:compute-tags) local-args) (let (... ... ... ... ...) (apply ... $
  byte-compile-body(((if (not ...) (apply ... ... ... local-args) (let ... ...))) nil)
  byte-compile-if((if (not (condition-case nil ... ...)) (signal (quote no-method-definition) (list ... local-args)) (if (not ...) (apply ... ... ... local-args) (let ... ...))))
  byte-compile-form((if (not (condition-case nil ... ...)) (signal (quote no-method-definition) (list ... local-args)) (if (not ...) (apply ... ... ... local-args) (let ... ...))) nil)
  byte-compile-top-level((progn (if (not ...) (signal ... ...) (if ... ... ...))) nil lambda)
  byte-compile-lambda((lambda (&rest local-args) "Return a sorted list of all ob:tags by name.\n\nCompute tag occurrence and their HTML percentage value.\n\nMIN_R and MAX_R are the min$
  eieio-defgeneric-form-primary-only-one(ob:compute-tags "Return a sorted list of all ob:tags by name.\n\nCompute tag occurrence and their HTML percentage value.\n\nMIN_R and MAX_R are$
  eieio-defmethod(ob:compute-tags (((self ob:backend) &optional min_r max_r) "Return a sorted list of all ob:tags by name.\n\nCompute tag occurrence and their HTML percentage value.\n\$
  (defmethod ob:compute-tags ((self ob:backend) &optional min_r max_r) "Return a sorted list of all ob:tags by name.\n\nCompute tag occurrence and their HTML percentage value.\n\nMIN_R$
  eval-buffer(#<buffer  *load*<2>> nil "/home/snerk/.emacs.d/o-blog/lisp/o-blog-backend.el" nil t)  ; Reading at buffer position 11934
  load-with-code-conversion("/home/snerk/.emacs.d/o-blog/lisp/o-blog-backend.el" "/home/snerk/.emacs.d/o-blog/lisp/o-blog-backend.el" nil t)
  require(o-blog-backend)
  (progn (require (quote eieio)) (require (quote o-blog-utils)) (require (quote o-blog-tag)) (require (quote o-blog-entry)) (require (quote o-blog-i18n)) (require (quote o-blog-backend$
  (eval-when-compile (require (quote eieio)) (require (quote o-blog-utils)) (require (quote o-blog-tag)) (require (quote o-blog-entry)) (require (quote o-blog-i18n)) (require (quote o-$
  eval-buffer(#<buffer  *load*> nil "/home/snerk/.emacs.d/o-blog/lisp/o-blog.el" nil t)  ; Reading at buffer position 581
  load-with-code-conversion("/home/snerk/.emacs.d/o-blog/lisp/o-blog.el" "/home/snerk/.emacs.d/o-blog/lisp/o-blog.el" nil nil)
  load("/home/snerk/.emacs.d/o-blog/lisp/o-blog.el" nil nil t)
  load-with-code-conversion("/home/snerk/.emacs.d/o-blog/lisp/o-blog.el" "/home/snerk/.emacs.d/o-blog/lisp/o-blog.el" nil nil)
  load("/home/snerk/.emacs.d/o-blog/lisp/o-blog.el" nil nil t)
  load-file("~/.emacs.d/o-blog/lisp/o-blog.el")
  call-interactively(load-file t nil)
  execute-extended-command(nil)
  call-interactively(execute-extended-command nil nil)
</code>

**Comment by renard** [comment]
You would probably want to try v2.5 branch https://github.com/renard/o-blog/tree/o-blog-v2.5

**Comment by zobi8225** [comment]
ok. It work with o-blog-v2.5
Thanks

**Comment by renard** [comment]
This is a transition until v3 is production ready.
