### ISSUE TITLE
Symbol's function definition is void

### ISSUE THREAD

**Issue by amsomniac** [renard/o-blog#135]
Migrating from o-blog to o-blogv2, tried o-blog-publish on my old blog.org file and got:

File mode specification error: (error ":END: line missing at position 716")
file-name-directory: Symbol's function definition is void: find-library-name

What needs changing? What can stay the same?

https://morphe.me/blog/blog.org < blog source file

**Comment by renard** [comment]
I guess your source is wrong `:` is missing after `:END`:

```org
  :PROPERTIES:
  :PAGE:     index.html
  :TEMPLATE: blog_static_no_title.html
  :END
------^
here
```
