### ISSUE TITLE
Spinner block the page

### ISSUE THREAD

**Issue by thomasluquet** [renard/o-blog#136]
Hi, i am little bit noob in web.

But the page created with sample.org is blocked by spin.min.js 
![spin](http://i.imgur.com/krpvCfn.png)

I got this message on the JS console 

> ReferenceError: Spinner is not defined index.html:14
> not well-formed articles.js:1
> TypeError: e is undefined o-blog.min.js:1
> not well-formed tags.js:1
> TypeError: ob_spinner is undefined

I am on o-blog 2.5 branch

**Comment by rbuchmann** [comment]
I have the same problem using the 2.5 branch and emacs 24.4.1 (with prelude).

**Comment by summaminutiae** [comment]
I had the same problem, too, in one of the branches.  To work around the
problem I just deleted what looked like the relevant <script>...</script>
call in one of the template files and all was well.

On Thu, Mar 12, 2015 at 7:28 AM, Rasmus Buchmann <notifications@github.com>
wrote:

> I have the same problem using the 2.5 branch and emacs 24.4.1 (with
> prelude).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/renard/o-blog/issues/136#issuecomment-78470619>.
>



-- 
Bill White . minutiae@gmail.com . http://members.wolfram.com/billw

**Comment by mlt** [comment]
Just rename `./templates/style/js/spin.js` into `spin.min.js` in that folder. See `./templates/page_header.html` for details. The spinner does look :candy:, no need to remove it :smile:
