### ISSUE TITLE
Random post 

### ISSUE THREAD

**Issue by igoumeninja** [renard/o-blog#137]
Dear all, I have a website about Greek Traditional Music (http://mousikobostani.github.io/) based on o-blog. I would like to add the functionality of random song-page. Is it possible? Any ideas?
Thanks in advance
Aris

**Comment by renard** [comment]
I guess the best is to customize the templates to use a piece of javascript to do the job.

A good place to start is the `templates/page_header.html`

**Comment by igoumeninja** [comment]
Done!
- http://arisearch.github.io/javascript/2015/03/12_random-page-collector.html
- http://mousikobostani.github.io//random.html
