### ISSUE TITLE
issue with npm install and version string

### ISSUE THREAD

**Issue by jave** [renard/o-blog#140]
npm install doesnt seem to like the version string "2.5" it wants instead "2.5.0".

this is the trace:
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'install' ]
2 info using npm@1.3.6
3 info using node@v0.10.33
4 error install Couldn't read dependencies
5 error Error: Invalid version: "2.5"
5 error     at Object.module.exports.fixVersionField (/usr/lib/node_modules/normalize-package-data/lib/fixer.js:175:13)
5 error     at /usr/lib/node_modules/normalize-package-data/lib/normalize.js:29:38
5 error     at Array.forEach (native)
5 error     at normalize (/usr/lib/node_modules/normalize-package-data/lib/normalize.js:28:15)
5 error     at final (/usr/lib/node_modules/read-package-json/read-json.js:310:33)
5 error     at then (/usr/lib/node_modules/read-package-json/read-json.js:124:33)
5 error     at /usr/lib/node_modules/read-package-json/read-json.js:299:40
5 error     at fs.js:271:14
5 error     at /usr/lib/node_modules/graceful-fs/graceful-fs.js:103:5
5 error     at Object.oncomplete (fs.js:107:15)
6 error If you need help, you may report this log at:
6 error     <http://github.com/isaacs/npm/issues>
6 error or email it to:
6 error     <npm-@googlegroups.com>
7 error System Linux 3.18.7-200.fc21.x86_64
8 error command "node" "/usr/bin/npm" "install"
9 error cwd /mnt/LogVol00/home/joakim/current/.emacs.d/el-get/o-blog
10 error node -v v0.10.33
11 error npm -v 1.3.6
12 verbose exit [ 1, true ]

**Comment by renard** [comment]
In fact you don't need it if you don't change the JS/CSS.

**Comment by jave** [comment]
Yes, but I'm trying to add a lightbox for viewing images. So far its not going too well.
If I change the version to 2.5.0 at least grunt/npm seems to be happy.
