### ISSUE TITLE
Fail to load o-blog: invalid-slot-name when loading with emacs 25.x

### ISSUE THREAD

**Issue by xmaillard** [renard/o-blog#159]
Hello,

in my quest to find a =orgmode= blogging/authoring tool I found o-blog.

Trying to load it returns:

``` emacs-lisp
Eager macro-expansion failure: (invalid-slot-name "#<ob:framework-component ob:framework-component>" lead) [2 times]
slot-missing: Invalid slot name: "#<ob:framework-component ob:framework-component>", lead
```

Here is my o-blog.conf file (loaded via emacs -Q):

``` emacs-lisp
;; -*- Mode: Emacs-Lisp -*-

(add-to-list 'load-path "~/git/o-blog/lisp")
(require 'o-blog)
```

Version informations:
GNU Emacs 25.1.50.1 (x86_64-apple-darwin15.0.0, NS appkit-1404.13 Version 10.11.1 (Build 15B42)) of 2015-12-03

OrgMode is from the /official/ GNU Emacs 25.x distribution.

Regards

**Comment by xmaillard** [comment]
I tried it with emacs 24.5 and it works. I will try to track down where it fails in eieio code tree.

**Comment by hanzejl** [comment]
I also have this problem with Emacs 25

**Comment by devminz** [comment]
-  I  also have same problem.  
-  I am using Spacemacs . 
-  My Emacs version is **26.0.50.2** 
- The error that is shown at startup is  

`Error in dotspacemacs/user-config: Invalid slot name: "#<ob:framework-component ob:framework-component>", lead
`

**Comment by Compro-Prasad** [comment]
Same problem here with Emacs 25.2 running Spacemacs.
