### ISSUE TITLE
Support for isolated files and TOC in blog posts

### ISSUE THREAD

**Issue by emish** [renard/o-blog#50]
Hi Sir,

I am very impressed with your work and really excited to start using o-blog. Hopefully when I am well-versed in elisp I can contribute some help.

As of right now, I find many of my posts in org-mode are tutorials or references, and so it would be of great value to me to have a table of contents on these pages, which tend to be quite long at times. As an example, http://emacsclub.github.com/html/emacs_intro.html

Is it possible to create blog posts that are linked to separate org-files, and then be able to generate a TOC on those pages? 

Thank you,
Mish

**Comment by cviebig** [comment]
+1 for TOC as in use [here](http://masato.github.io/2014/11/05/how-to-correctly-remove-volume-directories/)
