### ISSUE TITLE
INCLUDING Blog Posts

### ISSUE THREAD

**Issue by geekinthesticks** [renard/o-blog#52]
I want to port my Jekyll powered bog to o-blog. I have a lot of posts, one file for post. I would like to avoid placing them in one big file, as I think it would probably end up growing too big to be manageable.

I was hoping to INCLUDE each file:
# +INCLUDE: "./posts/2012-09-06-sea-to-summit-xmug.org"

File contains:

*\* DONE Sea to Summit X-Mug. :o@blog:
  CLOSED: [2012-10-18 Thu]

I managed to crack my plastic mug and was about to buy another one
when I decided to investigate the alternatives. I don't like metal
mugs of any sort. I end up burning my finger and lips whenever I use

However, it appears that the TODO header doesn't get processed. If I do it like this in the sample.org file:

*\* DONE Sea to Summit X-Mug. :o@blog:
  CLOSED: [2012-10-18 Thu]
# +INCLUDE: "./posts/2012-09-06-sea-to-summit-xmug.org"

Where the include just contains the body text it works. I guess I can live with having all the headers and just including the body text, but is it possible to get o-blog to process the DONE section in an included file?

**Comment by jave** [comment]
isnt this fixed now? I use #INCLUDE all the time!
