### ISSUE TITLE
Export broken: Invalid face

### ISSUE THREAD

**Issue by blitz** [renard/o-blog#65]
I installed as documented and then tried to org-publish-blog sample.org. I got "Invalid face" from the htmlize library (see backtrace below). 

Org-version: 7.8.11
htmlize: 1.34
Emacs: 24.2.1

Debugger entered--Lisp error: (error "Invalid face")
  internal-get-lisp-face-attribute(nil :height nil)
  face-attribute(nil :height)
  htmlize-face-size(default)
  htmlize-face-to-fstruct(default)
  htmlize-make-face-map((default))
  htmlize-buffer-1()
  htmlize-region(1 62)
  org-export-htmlize-region-for-paste(1 62)
  org-export-format-source-code-or-example("bash" "cd ~/.emacs.d\ngit clone https://github.com/renard/o-blog.git\n" " " 0 nil)
  org-export-replace-src-segments-and-examples()
  org-export-preprocess-string("#+OPTIONS: H:7 num:nil  toc:nil d:nil todo:nil <:nil pri:nil ...
[snip]

**Comment by scfc** [comment]
htmlize 1.34 is/was not compatible with Emacs 23 and later.  (Are you using Fedora?)  So you'd need to update htmlize to (probably) fix this.
