### ISSUE TITLE
q about inner buffer #+

### ISSUE THREAD

**Issue by unkcp** [renard/o-blog#76]
Hello, I am a newbie.
I don't know how to use `#+DEFAULT_CATEGORY` and `#+DISQUS` .etc.  and i search them in org manual but find nothing. and i even use `grep` to find them in the `.emacs.d/o-blog/` . 
where can i learn how to use them. 
thank you.

**Comment by cviebig** [comment]
There seems to be a list of options in [lisp/o-blog-obsolete.el](https://github.com/renard/o-blog/blob/master/lisp/o-blog-obsolete.el):

	file buffer publish-dir template-dir style-dir
	assets-dir posts-filter static-filter snippet-filter title
	description url language post-build-shell default-category
	disqus analytics filename-sanitizer posts-sorter posts-filepath
	posts-htmlfile

I don't know more but maybe that's a starting point?
